---
title: "Proto-Greek"
output: 
  html_document:
    includes:
      in_header: "favicon.html"
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>
## Collaborative speech perception project

We will embark on a project that takes what we're learning in the seminar and applies it to a problem in historical phonology. The project is collaborative, which in this context means that each of you will contribute equally to the research, design, and execution of a pilot research experiment. We will discuss various aspects of the design and execution of the project during every meeting, but it will be expected that students dedicate some lab time to working on various parts of the experiment. I will also be *very* involved in all aspects of the project and hopefully we'll have something presentable by the end of the term. The goal will be to have a poster presentation at a conference like the Acoustical Society of America or Laboratory Phonology.

## The problem: Proto-Greek labiovelars

It was hypothesized that an early stage of Greek had labiovelars and that they corresponded to either labial or coronal stops (**but never velars**), and we confirmed this because [Linear B](https://en.wikipedia.org/wiki/Linear_B) has a <q_> series: 𐀣 <qa> 𐀤 <qe> 𐀥 <qi> 𐀦 <qo> which is used for where we hypothesized \*kʷ, \*gʷ, \*gʷʰ.

In [centum languages](https://en.wikipedia.org/wiki/Centum_and_satem_languages) these became velars across the board, but the following happens in Greek (I'll use kʷ as a stand-in for the three-way labial contrast): 

(1)   kʷ > t / __ [-Back] (e.g., PIE \*penkʷe  'five' > Gk πέντε 'group of five'<br>       kʷ > p / elsewhere (e.g., Myc. qo-u-ko-roi, Gk. βουκόλος 'cowherd')

But [Sihler](pdfs/sihler1995selection.pdf) writes there is a lot of leveling in favor of the labials, and there may be some dialect effects too. 

There are a few things slightly novel here: 

a. that neither reflex is dorsal
b. that -Back partitions the space into labial and coronal reflexes in the precise way it does
c. that there's leveling towards the labial

**The question for our class is whether we can simulate any of this in the lab.**

## Approach

Our goal is to induce an acoustic scenario for the listener such that the signal is obscured. How do we do this? With noise of various types. We then embed the signal (our kw sounds) in the noise and ask listeners what they hear. Do they hear a "k", "p," "t"? What's the best way to ask this?

## The signal

The Greek data show that kw- changes to *p* or *t* depending on the following vowel: kwi and kwe > ti and te; kwu and kwo > pu and po. So we need to record signal stimuli that encompass all of the appropriate vowel contexts. Do we do this using monosyllables or words (in English)? What are the advantages/disadvantages of both?

### Recording the stimuli

Once we've decided on the structure of the stimuli (monosyllables or words) we have to come up with a "speech materials" list for recording.

- List of words (how many?)
  - Write down all of the minimally different words in English with p/t/k/kw- (e.g. pick, tick, kick, quick) in various vowel contexts
- If words we need to think about frequency. Let's talk about [SUBTLEX](https://shiny.psychology.nottingham.ac.uk/lpzwjv/SUBTLEX-UK/)
- Record a list of words or words embedded in sentences of the form "Say the wor X again"; advantages/disadvantages

The approach we'll take is a "cross-linguistic" speech perception task. The idea here is that the listener will be a non-native listener. In some sense they are naive to the phonology of the language they will be hearing in the experiment. English *does* have [kw-] but the problem is that it is typically aspirated. 

This is likely the problem with the Beeley's dissertation (please skim [this](pdfs/Beeley_et_al_2016_The_Phonetics_of.pdf)) that attempted to do what we're trying here. There were no papers published from it (it's an Oxford phonetics dissertation!) likely because she didn't find an effect. I think the problem was in the design of her stimuli and experiment. I think aspiration gives the listener **a lot** of acoustic information in the aspiration noise as to the place of articulation the initial stop. People simply heard [k], even in noise.

What we'll be doing is presenting listeners with [kw-] but in a language other than English. It looks like [Cantonese](https://en.wikipedia.org/wiki/Cantonese_phonology#Initial_consonants) has phonemic /kw-/ and /kwh-/, so potentially we can record a Cantonese speaker saying [kwi-], [kwu-], [kwa-], etc. But first we'll have to check to make sure they are photactically possible in Cantonese.

The task will ask listeners to guess what English word is being said having only heard the first syllable in noise. This means that you have to record not only **target** syllables, but also non-target syllables (i.e., p-, t-, k-).

I recommend that the speaker record at least 5 "takes" of each syllable. If it is in Cantonese, what tone should be used? What about list intonation? Randomize the word list so that there is no repetition of the overall reading leading to "list intonation."

## Housekeeping

We will use this [folder](https://drive.google.com/drive/folders/1NqkTmzsVbxEUuBIg3wK_H767pT1mKdD6?usp=sharing) for all of the files associated with the project:

- Word list for stimuli
- All audio files
- spreadsheet for stimuli acoustics
- Drafts of writeup

## Acoustics


